language: node_js #Specifying the server
node_js: #All the versions supported
- '6'
- '7'
- '7.6'
- '8'
services: #mariadb database 
- mysql
#before_install:
  #- mysql -u root --password="" < test/travis.sql
cache: #speed up build time on Travis by not having to npm every time.
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: webapp_upload #uploads the server folder of the code to S3
  skip_cleanup: true
  on: &2
    repo: $REPO_NAME
    branch: Assignment07-08
  bucket: $S3_BUCKET
  region: $S3_REGION 
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  key: webapp.zip
  bundle_type: zip
  application: $APP_NAME
  deployment_group: $DEPLOYMENT_GRP
  region: $S3_REGION
  on: *2
script:
  - zip -r webapp *
  - mkdir -p webapp_upload
  - mv webapp.zip webapp_upload/webapp.zip
