version: 0.0
os: linux
files:
  - source: /webapp/
    destination: /home/centos/webapp
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ec2-user
