version: 0.0
os: linux
files:
  - source: /webapp/
    destination: /home/ubuntu/webapp
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60
