version: 0.0
os: linux
files:
  - source: /webapp/
    destination: /home/centos/webapp
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 100
      
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 200
      
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
 
  ApplicationStop:
   - location: scripts/stop.sh
     timeout: 120
